&lt;!DOCTYPE html&gt;
&lt;html lang="es"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
    &lt;title&gt;Calculadora&lt;/title&gt;
    &lt;link rel="stylesheet" href="css/style.css"&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;div class="calculator"&gt;
        &lt;h1&gt;Calculadora&lt;/h1&gt;
        &lt;form method="post" action=""&gt;
            &lt;input type="number" step="any" name="num1" placeholder="Número 1" required&gt;
            &lt;select name="operation" required&gt;
                &lt;option value="+"&gt;Suma (+)&lt;/option&gt;
                &lt;option value="-"&gt;Resta (-)&lt;/option&gt;
                &lt;option value="*"&gt;Multiplicación (*)&lt;/option&gt;
                &lt;option value="/"&gt;División (/)&lt;/option&gt;
                &lt;option value="%"&gt;Porcentaje (%)&lt;/option&gt;
            &lt;/select&gt;
            &lt;input type="number" step="any" name="num2" placeholder="Número 2" required&gt;
            &lt;button type="submit" name="calculate"&gt;Calcular&lt;/button&gt;
        &lt;/form&gt;
        &lt;?php if ($data['result'] !== null): ?&gt;
            &lt;p class="result"&gt;Resultado: &lt;?php echo htmlspecialchars($data['result']); ?&gt;&lt;/p&gt;
        &lt;?php endif; ?&gt;
        &lt;h2&gt;Historial&lt;/h2&gt;
        &lt;ul class="history"&gt;
            &lt;?php foreach ($data['history'] as $entry): ?&gt;
                &lt;li&gt;&lt;?php echo htmlspecialchars($entry); ?&gt;&lt;/li&gt;
            &lt;?php endforeach; ?&gt;
        &lt;/ul&gt;
        &lt;form method="post" action=""&gt;
            &lt;button type="submit" name="clear_history"&gt;Borrar Historial&lt;/button&gt;
        &lt;/form&gt;
    &lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;